version: '3.8'

services:
  web:
    build: .
    command: bundle exec rails server -b 0.0.0.0 -p $PORT  # Use dynamic port
    volumes:
      - .:/app
    environment:
      - PORT=$PORT  # Set the PORT variable if necessary