version: '3.8'

services:
  web:
    build: .
    command: bundle exec rails server -b 0.0.0.0 -p 8081  # Set the app to listen on port 8081
    volumes:
      - .:/app
    ports:
      - "80:8081"  # Map port 8081 in the container to port 80 on the host
