# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: Ruby on Rails CI

on:
  push:
    branches:
      - master
      - development
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.2 # Specify the Ruby version you're using
        bundler-cache: true # Enable bundler caching for faster builds

    - name: Verify Ruby Version and Permissions
      run: |
        chmod +x bin/*
        sed -i 's/ruby.exe/ruby/' bin/*

    - name: Install dependencies
      env:
        RAILS_ENV: test
      run: |
        bundle install --jobs 4 --retry 3
      #simplecov will run under this also 
    - name: Run RSpec tests
      env:
        RAILS_ENV: test
      run: |
        bundle exec rspec

    - name: Run BDD tests
      env:
        RAILS_ENV: test
      run: bin/rails cucumber  

    - name: Run RuboCop
      env:
        RAILS_ENV: test
      run: bundle exec rubocop --fail-level=error # only show errors

    - name: Run Dependency Vulnerability Scanning
      run: bundle exec bundler-audit check --update

    - name: Run E2E tests
      env:
        RAILS_ENV: test
      run: |
        bundle exec rspec spec/features/homepage_spec.rb
        mkdir -p test-results

    - name: Publish Test Results
      uses: actions/upload-artifact@v4
      with:
        name: Capybara E2E Tests
        path: test-results/e2etests.xml


